/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adivinaelvaso;

import java.util.Random;
import javax.swing.*;

/**
 *
 * @author Gabriel
 */
public class Adivinalo extends javax.swing.JFrame {

    /**
     * Creates new form Adivinalo
     */
    public Adivinalo() {
        initComponents();
        botonV1.setEnabled(false);
        botonV2.setEnabled(false);
        botonV3.setEnabled(false);
    }
    int vasos [] = new int [3];
    int vaso1, vaso2, vaso3;
    double apuesta, cobro;
    Random rnd = new Random();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        botonV1 = new javax.swing.JButton();
        botonV2 = new javax.swing.JButton();
        botonV3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        labelMensaje = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        labelCobro = new javax.swing.JLabel();
        butonReglas = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 36)); // NOI18N
        jLabel1.setText("Bienvenido a adivina el vaso");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 63, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vaso.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 11, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("apuesta");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 201, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 201, 43, -1));

        jButton1.setText("Apostar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 200, -1, -1));

        botonV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vasoAl.png"))); // NOI18N
        botonV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonV1ActionPerformed(evt);
            }
        });
        getContentPane().add(botonV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 336, -1, -1));

        botonV2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vasoAl.png"))); // NOI18N
        botonV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonV2ActionPerformed(evt);
            }
        });
        getContentPane().add(botonV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 336, -1, -1));

        botonV3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vasoAl.png"))); // NOI18N
        botonV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonV3ActionPerformed(evt);
            }
        });
        getContentPane().add(botonV3, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 336, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jLabel4.getAccessibleContext().setAccessibleName("labelMensaje");

        getContentPane().add(labelMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 605, -1, -1));

        jButton2.setText("Jugar otra vez");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 687, -1, -1));
        getContentPane().add(labelCobro, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 630, -1, -1));

        butonReglas.setText("Instrucciones");
        butonReglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonReglasActionPerformed(evt);
            }
        });
        getContentPane().add(butonReglas, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 200, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dados.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        apuesta = Double.parseDouble(jTextField1.getText());
        vasos[0]=rnd.nextInt(3)+1;
        if(vasos[0]!=3){
            vasos[1]=rnd.nextInt(3)+1;
            if(vasos[1]!=3){
                vasos[2]=3;
            } else{
                vasos[2]=1;
            }
        } else{
            vasos[1]=1;
            vasos[2]=1;
        }

        jTextField1.setEditable(false);
        botonV1.setEnabled(true);
        botonV2.setEnabled(true);
        botonV3.setEnabled(true);
        for (int i = 0; i < 3; i++) {
            System.out.println(vasos[i]);
        }
        System.out.println("");
        jButton1.setEnabled(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonV1ActionPerformed
        if (vasos[0] == 3) {
            botonV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vasoBol.png")));
            labelMensaje.setText("Adivinaste, duplicaste la apuesta!!");
            cobro = apuesta * 2;
            labelCobro.setText("Felicitaciones ganaste " + cobro);
            botonV2.setEnabled(false);
            botonV3.setEnabled(false);
        } else {
            labelMensaje.setText("No adivinaste, perdiste todo");
            labelCobro.setText("Perdiste :(");
            botonV1.setEnabled(false);
            botonV2.setEnabled(false);
            botonV3.setEnabled(false);
        }
    }//GEN-LAST:event_botonV1ActionPerformed

    private void botonV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonV2ActionPerformed
        if (vasos[1] == 3) {
            botonV2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vasoBol.png")));
            labelMensaje.setText("Adivinaste, duplicaste la apuesta!!");
            cobro = apuesta * 2;
            labelCobro.setText("Felicitaciones ganaste " + cobro);
            botonV1.setEnabled(false);
            botonV3.setEnabled(false);
        } else {
            labelMensaje.setText("No adivinaste, perdiste todo");
            labelCobro.setText("Perdiste :(");
            botonV1.setEnabled(false);
            botonV2.setEnabled(false);
            botonV3.setEnabled(false);
        }
    }//GEN-LAST:event_botonV2ActionPerformed

    private void botonV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonV3ActionPerformed
        if (vasos[2] == 3) {
            botonV3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vasoBol.png")));
            labelMensaje.setText("Adivinaste, duplicaste la apuesta!!");
            cobro = apuesta * 2;
            labelCobro.setText("Felicitaciones ganaste " + cobro);
            botonV1.setEnabled(false);
            botonV2.setEnabled(false);

        } else {
            labelMensaje.setText("No adivinaste, perdiste todo");
            labelCobro.setText("Perdiste :(");
            botonV1.setEnabled(false);
            botonV2.setEnabled(false);
            botonV3.setEnabled(false);
        }
    }//GEN-LAST:event_botonV3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText("");
        jTextField1.setEditable(true);
        botonV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vasoAl.png")));
        botonV2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vasoAl.png")));
        botonV3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vasoAl.png")));
        labelMensaje.setText("");
        for (int i = 0; i < 3; i++) {
            vasos[i]=1;
        }
        vaso1 = 1;
        vaso2 = 1;
        vaso3 = 1;
        jButton1.setEnabled(true);
        botonV1.setEnabled(true);
        botonV2.setEnabled(true);
        botonV3.setEnabled(true);
        labelCobro.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void butonReglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonReglasActionPerformed
       new Reglas().setVisible(true);
    }//GEN-LAST:event_butonReglasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adivinalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adivinalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adivinalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adivinalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adivinalo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonV1;
    private javax.swing.JButton botonV2;
    private javax.swing.JButton botonV3;
    private javax.swing.JButton butonReglas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelCobro;
    private javax.swing.JLabel labelMensaje;
    // End of variables declaration//GEN-END:variables
}
